name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run dist
